$(document).ready(function(){
    $('.btn-menu').click(function(){
        if($('#menu').hasClass('hide')){
            $('#menu').removeClass('hide');
            $('#menu').addClass('menu');
        }
        else{
            $('#menu').removeClass('menu');
            $('#menu').addClass('hide');
        }
    });
    $(window).scroll(function(){
        if($(document).scrollTop() > 0){
            if($('#menu').hasClass('menu')){
                $('#menu').removeClass('menu');
                $('#menu').addClass('hide');
            }
        }
    })
});